"""fix_user_model_and_username

Revision ID: 41be98996712
Revises: cb96f779441b
Create Date: 2026-05-14 15:08:26.860464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '41be98996712'
down_revision: Union[str, Sequence[str], None] = 'cb96f779441b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'monitor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('monitor', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('monitor', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'username')
    op.drop_column('user', 'last_name')
    op.alter_column('monitor', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('monitor', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alert', 'monitor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
