"""make condition nullable or remove it

Revision ID: bd81f13b3fab
Revises: ff4b8a2e0cb8
Create Date: 2026-06-29 17:48:55.731436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "bd81f13b3fab"
down_revision: Union[str, Sequence[str], None] = "ff4b8a2e0cb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitor", "condition")
    op.drop_column("monitor", "target_value_str")
    op.drop_column("monitor", "target_value_num")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitor",
        sa.Column(
            "target_value_num",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "monitor",
        sa.Column("target_value_str", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "monitor",
        sa.Column("condition", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
